export type Project = {
  slug: string;
  name: string;
  client: string;
  category: "Residential" | "Commercial" | "Renovation" | "Furniture Design";
  type: string;
  location: string;
  building: string;
  year: string;
  status: "Completed" | "In Progress" | "Design Phase";
  scope: string[];
  concept: string;
  story: string;
  heroImage: string;
  galleryImages: string[];
  drawingImages: DrawingImage[];
  featured: boolean;
  order: number;
};

export type DrawingImage = {
  src: string;
  label: string;
};

const projects: Project[] = [
  {
    slug: "gita-residence",
    name: "Gita Residence",
    client: "Gita Residence",
    category: "Residential",
    type: "4BHK Residence",
    location: "Bandra",
    building: "Evergreen Raheja",
    year: "Needs Clarification",
    status: "Completed",
    scope: [
      "Complete Interior Design & Execution",
      "Space Planning",
      "Material Selection",
      "Site Coordination",
      "Vendor Coordination",
      "Site Supervision",
      "Final Execution",
    ],
    concept:
      "A modern family home designed with contemporary textures, clean detailing, and deeply personalised spaces. The design language was tailored to reflect the client's preferences while maintaining functionality and comfort across all four bedrooms.",
    story:
      "The Gita Residence in Bandra is a study in layered contemporary living. A curved bouclé sofa anchors the living room against a dramatic bookmatched marble bookcase, while the mandir — backlit in glowing onyx with a hand-painted chinoiserie ceiling panel — becomes the spiritual heart of the home. A curated terracotta tile art installation adds cultural warmth to the formal spaces. Each bedroom was individually tailored: the master suite features bespoke joinery and a dressing area, while the children's rooms balance personality with practicality. The project was delivered end-to-end, from concept development through contractor coordination and final handover.",
    heroImage: "/images/gita/57dc177d-3eb0-4b87-8148-33b3380aaa2a.jpg",
    galleryImages: [
      "/images/gita/57dc177d-3eb0-4b87-8148-33b3380aaa2a.jpg",
      "/images/gita/4bd4102e-851d-48a7-8f6d-ce92df999c1e.jpg",
      "/images/gita/0f7093f1-6081-472c-828c-ebc458b0c2e7.jpg",
      "/images/gita/3cbc7b9e-fbc0-47c6-ac72-d3ee8cceb2c5.jpg",
      "/images/gita/4db604ec-c1aa-4839-bb99-e30d93fe11dc.jpg",
      "/images/gita/54a71aa1-7938-4a9e-a049-6b200c30356b.jpg",
      "/images/gita/55471595-be1f-450d-8a4a-e797cbd03451.jpg",
      "/images/gita/61200854-3ba4-43ba-bacf-efbd8c7cadb8.jpg",
      "/images/gita/67a3ad5d-1899-44ec-8764-9cdc808ba5bf.jpg",
      "/images/gita/78f22306-9b0f-46c2-a123-621b37ea9d78.jpg",
      "/images/gita/8bfc6a1a-581e-41a0-9406-425d1da221fe.jpg",
      "/images/gita/9854f0e9-37c8-464d-8928-2726d64c16dc.jpg",
      "/images/gita/a84c2e4a-595a-4024-9879-e95ff2d46c61.jpg",
      "/images/gita/ad2ff423-3f70-43b5-b041-c0f2d5eb25ab.jpg",
      "/images/gita/b7282c09-803f-4928-89ed-0067ed32024a.jpg",
      "/images/gita/bfa68d29-df60-471e-8a5c-ee724fd41a41.jpg",
      "/images/gita/c77ba17f-46ca-4d08-ba2a-82295fd64ba4.jpg",
      "/images/gita/dfb2f41b-303a-47bf-b2da-241aa03aeae2.jpg",
      "/images/gita/e3e4e37d-848d-4d78-975f-b4f96a613bcd.jpg",
      "/images/gita/eba51249-1aef-42d1-8544-072ec3103e85.jpg",
      "/images/gita/f93c36f4-cfae-4071-a4ff-cf3c240b0420.jpg",
      "/images/gita/1768075f-dd2b-4d92-8fd3-60616079a311.jpg",
      "/images/gita/220b5adc-53ae-47bd-b700-84493446fba2.jpg",
      "/images/gita/2360d9f5-edba-4b58-b251-1b63b4866e97.jpg",
      "/images/gita/241f4bf7-10bb-4cf1-9c1b-0734c474553d.jpg",
      "/images/gita/2452f03e-0bc6-4ff7-8fe8-f4b3af324234.jpg",
      "/images/gita/344b2cdd-89b4-45e5-bc1c-56ed7c36eab8.jpg",
      "/images/gita/3e325f60-b7e8-49b8-92e0-e97d84b0ce20.jpg",
      "/images/gita/523a5b99-a91c-4909-93b6-aa53d36e782d.jpg",
    ],
    drawingImages: [
      { src: "/images/gita/drawings/master-bedroom-layout.jpg", label: "Master Bedroom Layout" },
      { src: "/images/gita/drawings/daughters-bedroom-layout.jpg", label: "Daughter's Bedroom Layout" },
      { src: "/images/gita/drawings/sons-bedroom-layout.jpg", label: "Son's Bedroom Layout" },
      { src: "/images/gita/drawings/parents-bedroom-layout.jpg", label: "Parents' Bedroom Layout" },
      { src: "/images/gita/drawings/bar-unit-elevation.jpg", label: "Bar Unit Elevation" },
      { src: "/images/gita/drawings/bathroom-elevations-p1.jpg", label: "Bathroom Elevations — 1" },
      { src: "/images/gita/drawings/bathroom-elevations-p2.jpg", label: "Bathroom Elevations — 2" },
      { src: "/images/gita/drawings/bathroom-elevations-p3.jpg", label: "Bathroom Elevations — 3" },
      { src: "/images/gita/drawings/bathroom-elevations-p4.jpg", label: "Bathroom Elevations — 4" },
      { src: "/images/gita/drawings/bathroom-elevations-p5.jpg", label: "Bathroom Elevations — 5" },
      { src: "/images/gita/drawings/bathroom-elevations-p6.jpg", label: "Bathroom Elevations — 6" },
      { src: "/images/gita/drawings/bathroom-elevations-p7.jpg", label: "Bathroom Elevations — 7" },
      { src: "/images/gita/drawings/daughters-study-unit.jpg", label: "Daughter's Study Unit" },
      { src: "/images/gita/drawings/sons-study-unit.jpg", label: "Son's Study Unit" },
      { src: "/images/gita/drawings/mandir.jpg", label: "Mandir" },
      { src: "/images/gita/drawings/master-bathroom.jpg", label: "Master Bathroom" },
      { src: "/images/gita/drawings/daughters-bathroom.jpg", label: "Daughter's Bathroom" },
      { src: "/images/gita/drawings/sons-bathroom.jpg", label: "Son's Bathroom" },
      { src: "/images/gita/drawings/powder-room.jpg", label: "Powder Room" },
    ],
    featured: true,
    order: 1,
  },
  {
    slug: "karwa-residence",
    name: "Karwa Residence",
    client: "Karwa Residence",
    category: "Residential",
    type: "10BHK Luxury Duplex",
    location: "Prabhadevi",
    building: "Rustomjee Crown",
    year: "Needs Clarification",
    status: "Completed",
    scope: [
      "Space Planning Support",
      "Elevation Design",
      "Fabric Selection",
      "Hardware Selection",
      "Lighting Selection",
      "Design Development",
    ],
    concept:
      "A luxury duplex residence designed to balance contemporary living with classical detailing — where modern modular functionality meets timeless mouldings, bespoke lighting, and curated material choices across ten bedrooms spanning two floors.",
    story:
      "The Karwa Residence at Rustomjee Crown, Prabhadevi presented a singular design challenge: create a cohesive identity across two floors of a 10BHK duplex, ensuring equal design value for the client's two sons while preserving the grandeur expected of the address. The design response weaves classical European detailing — elaborate crown mouldings, carved decorative appliqués, ornate chandeliers — with the efficiency of contemporary modular systems. The master bedroom takes centre stage with a show-stopping window view of the Mumbai skyline. Bespoke bathroom vanities in warm stone and sculptured tile walls elevate the private spaces, while the double-height foyer and living areas on both floors maintain visual consistency throughout.",
    heroImage: "/images/karwa/26247b2f-3562-4571-b08b-bfeb55e2fb38.jpg",
    galleryImages: [
      "/images/karwa/26247b2f-3562-4571-b08b-bfeb55e2fb38.jpg",
      "/images/karwa/6680d803-c931-442b-879a-d529931c2de6.jpg",
      "/images/karwa/000145d8-6123-4140-bac7-bf7f22c47f91.jpg",
      "/images/karwa/08432ad5-051c-41ea-93aa-512e803a0442.jpg",
      "/images/karwa/0928f110-d73e-46e6-a21f-f031e0387364.jpg",
      "/images/karwa/0fb32576-ce2b-439d-90a0-086c1824c720.jpg",
      "/images/karwa/26452e0b-5136-4ce2-90ae-e4e9ee2d4b10.jpg",
      "/images/karwa/2e69ff60-637e-4ff7-af78-ac7f95e376f3.jpg",
      "/images/karwa/2fe3859c-a689-497e-97ca-57233b366488.jpg",
      "/images/karwa/325958f7-e78a-47ed-85c0-bfa2d8398c07.jpg",
      "/images/karwa/37e6bc1f-9d60-44be-a086-3fb0b4bdd18b.jpg",
      "/images/karwa/502fd813-c718-4a61-a2cb-3abcacbdd57c.jpg",
      "/images/karwa/525157e1-b9d4-4fd1-b313-3c335f59fbc9.jpg",
      "/images/karwa/527b91fb-799c-4a9a-b972-492e3771a3b5.jpg",
      "/images/karwa/54b40eb3-ed90-4df4-b4d6-e95fcaa91752.jpg",
      "/images/karwa/591cdd41-16b9-489e-a645-695d678b6c02.jpg",
      "/images/karwa/59650c19-80b2-4a01-9f66-6eea8537f02d.jpg",
      "/images/karwa/5d0b4588-0277-4f2c-82ef-e56c7ae839a9.jpg",
      "/images/karwa/5ed710bb-41c2-4911-a4b8-c4a6b3e81af6.jpg",
      "/images/karwa/6243fb5d-79ab-46a0-9cde-a0d28602e795.jpg",
      "/images/karwa/64838227-d80e-422f-b837-26fdf1314f23.jpg",
      "/images/karwa/66f6bd07-eb79-4ec0-8106-e9839ae2984c.jpg",
      "/images/karwa/6a07151f-7e07-4e89-96b4-581068d811ac.jpg",
      "/images/karwa/6bd95dfd-a1b8-4997-9e36-ff65cce6fb4e.jpg",
      "/images/karwa/74f3c429-8fca-46c1-90d4-85ed587bd42a.jpg",
      "/images/karwa/771d8d24-da44-40ac-b74a-d945e1fc68b2.jpg",
      "/images/karwa/7777b5b3-030d-4b5c-83db-966b2baf51b1.jpg",
      "/images/karwa/78a8501c-5e39-4eba-a65c-d9503e420c3a.jpg",
      "/images/karwa/7d54a524-9b6b-437d-89de-510fd2d72397.jpg",
      "/images/karwa/8ac43306-b0b2-4fb1-b16f-f81cd28212ee.jpg",
      "/images/karwa/93ba0c44-c5ec-4d31-be55-f27cfc67fc53.jpg",
      "/images/karwa/96eb29b4-1e8b-4a94-9846-4385f927b4bb.jpg",
      "/images/karwa/970b1a2f-8cef-44e7-9cee-8bd4a74af99c.jpg",
      "/images/karwa/9b60a49a-4b67-4079-88e8-4726b8c71c63.jpg",
      "/images/karwa/9d44d2bc-3562-4c60-86a0-2a3e0c2af0c2.jpg",
      "/images/karwa/9f64c8ce-1362-44e8-b526-bbea2a84fbef.jpg",
      "/images/karwa/a1322146-46f8-418a-a066-5a5a0a60956c.jpg",
      "/images/karwa/a13bfd22-424c-4dea-886e-848cdbc9a82a.jpg",
      "/images/karwa/a2404a67-23cf-47ac-b193-5c437ea60c33.jpg",
      "/images/karwa/a741a19f-92b2-4a67-ace3-25a5d4db53a6.jpg",
      "/images/karwa/a9833a3b-03f5-468a-9035-ac7dd47653f3.jpg",
      "/images/karwa/acb33a90-909a-4bf6-9cd3-debf9361b722.jpg",
      "/images/karwa/ae4d70d9-d708-49ca-8453-849bbf448fd0.jpg",
      "/images/karwa/b093a8f4-e219-4f1e-93e4-687b15d36189.jpg",
      "/images/karwa/b164cbac-299f-4279-ae2a-294e1be43c21.jpg",
      "/images/karwa/b7a53d83-fecf-4ee2-91fc-5bb11978f5ca.jpg",
      "/images/karwa/b8c4a2f3-ffb2-4ac3-9ca9-16125e800745.jpg",
      "/images/karwa/c660ef87-af67-496b-9515-023853d2c3e2.jpg",
      "/images/karwa/c6fb35b8-eadd-4d9a-938c-f4fe07c6e26c.jpg",
      "/images/karwa/c73578ef-2731-46aa-ac6b-361be0994658.jpg",
      "/images/karwa/c860034d-6f1f-489a-a817-631e83c9796e.jpg",
      "/images/karwa/cd42a210-b3fe-4850-a09d-a52c1e974787.jpg",
      "/images/karwa/d7a70f33-ba7e-4317-8289-438045bea5cf.jpg",
      "/images/karwa/df0b064e-1dfb-4d4d-be1f-f06f9fc541db.jpg",
      "/images/karwa/df82ed26-5387-466e-a732-d05ec014df24.jpg",
      "/images/karwa/e214cf0d-66c7-485a-8777-fbf27b550a1f.jpg",
      "/images/karwa/f0bdd14e-8c6d-4b5a-b0f2-70444e7d3719.jpg",
      "/images/karwa/f2a4c3f9-844c-47e9-9de8-20789ccf4235.jpg",
    ],
    drawingImages: [
      { src: "/images/karwa/drawings/final-renders-p1.jpg", label: "Final Renders — 1" },
      { src: "/images/karwa/drawings/final-renders-p2.jpg", label: "Final Renders — 2" },
      { src: "/images/karwa/drawings/final-renders-p3.jpg", label: "Final Renders — 3" },
      { src: "/images/karwa/drawings/final-renders-p4.jpg", label: "Final Renders — 4" },
      { src: "/images/karwa/drawings/final-renders-p5.jpg", label: "Final Renders — 5" },
      { src: "/images/karwa/drawings/final-renders-p6.jpg", label: "Final Renders — 6" },
      { src: "/images/karwa/drawings/final-renders-p7.jpg", label: "Final Renders — 7" },
      { src: "/images/karwa/drawings/final-renders-p8.jpg", label: "Final Renders — 8" },
      { src: "/images/karwa/drawings/final-renders-p9.jpg", label: "Final Renders — 9" },
      { src: "/images/karwa/drawings/final-renders-p10.jpg", label: "Final Renders — 10" },
      { src: "/images/karwa/drawings/final-renders-p11.jpg", label: "Final Renders — 11" },
      { src: "/images/karwa/drawings/final-renders-p12.jpg", label: "Final Renders — 12" },
      { src: "/images/karwa/drawings/final-renders-p13.jpg", label: "Final Renders — 13" },
      { src: "/images/karwa/drawings/final-renders-p14.jpg", label: "Final Renders — 14" },
      { src: "/images/karwa/drawings/final-renders-p15.jpg", label: "Final Renders — 15" },
      { src: "/images/karwa/drawings/final-renders-p16.jpg", label: "Final Renders — 16" },
      { src: "/images/karwa/drawings/final-renders-p17.jpg", label: "Final Renders — 17" },
      { src: "/images/karwa/drawings/final-renders-p18.jpg", label: "Final Renders — 18" },
      { src: "/images/karwa/drawings/final-renders-p19.jpg", label: "Final Renders — 19" },
      { src: "/images/karwa/drawings/final-renders-p20.jpg", label: "Final Renders — 20" },
      { src: "/images/karwa/drawings/final-renders-p21.jpg", label: "Final Renders — 21" },
      { src: "/images/karwa/drawings/final-renders-p22.jpg", label: "Final Renders — 22" },
      { src: "/images/karwa/drawings/final-renders-p23.jpg", label: "Final Renders — 23" },
      { src: "/images/karwa/drawings/final-renders-p24.jpg", label: "Final Renders — 24" },
      { src: "/images/karwa/drawings/final-renders-p25.jpg", label: "Final Renders — 25" },
      { src: "/images/karwa/drawings/final-renders-p26.jpg", label: "Final Renders — 26" },
      { src: "/images/karwa/drawings/final-renders-p27.jpg", label: "Final Renders — 27" },
      { src: "/images/karwa/drawings/final-renders-p28.jpg", label: "Final Renders — 28" },
      { src: "/images/karwa/drawings/bed-designs-p1.jpg", label: "Bed Designs — 1" },
      { src: "/images/karwa/drawings/bed-designs-p2.jpg", label: "Bed Designs — 2" },
      { src: "/images/karwa/drawings/bed-designs-p3.jpg", label: "Bed Designs — 3" },
      { src: "/images/karwa/drawings/bed-designs-p4.jpg", label: "Bed Designs — 4" },
      { src: "/images/karwa/drawings/bed-designs-p5.jpg", label: "Bed Designs — 5" },
      { src: "/images/karwa/drawings/bed-designs-p6.jpg", label: "Bed Designs — 6" },
      { src: "/images/karwa/drawings/fancy-lights-p1.jpg", label: "Fancy Lights — 1" },
      { src: "/images/karwa/drawings/fancy-lights-p2.jpg", label: "Fancy Lights — 2" },
      { src: "/images/karwa/drawings/fancy-lights-p3.jpg", label: "Fancy Lights — 3" },
      { src: "/images/karwa/drawings/fabric-selection.jpg", label: "Fabric Selection" },
    ],
    featured: true,
    order: 2,
  },
  {
    slug: "dave-residence",
    name: "Dave Residence",
    client: "Dave Residence",
    category: "Residential",
    type: "3BHK Residence",
    location: "Santacruz",
    building: "Arkade Aura",
    year: "2025",
    status: "Completed",
    scope: [
      "Client Meetings & Design Planning",
      "Material Selection",
      "Vendor & Contractor Coordination",
      "Site Supervision",
      "Procurement Assistance",
      "Budget & Billing Coordination",
      "Final Styling & Handover",
    ],
    concept:
      "A clean, warm residential interior where white and natural wood create a bright, lifestyle-oriented home — brass accents and moulded panelling lending a quiet elegance throughout.",
    story:
      "The Dave Residence at Arkade Aura, Santacruz was managed end-to-end — from the first client meeting through final handover. The design brief called for a fresh, liveable home that felt elevated without being formal. The response: a white modular kitchen with warm brass hardware, a dining area framed by a classic panel-moulded wall and pendant lighting, and a living room that balances comfort with restraint. The daughter's room introduces a fresh green accent palette and natural wood flooring to reflect her personality, while the master bedroom and parent's suite prioritise calm and storage efficiency.",
    heroImage: "/images/dave/_DSC6777.JPG.jpeg",
    galleryImages: [
      "/images/dave/_DSC6777.JPG.jpeg",
      "/images/dave/_DSC6767.JPG.jpeg",
      "/images/dave/_DSC6768.JPG.jpeg",
      "/images/dave/DSC_6776.JPG.jpeg",
      "/images/dave/_DSC6778.JPG.jpeg",
      "/images/dave/_DSC6785.JPG.jpeg",
      "/images/dave/_DSC6786.JPG.jpeg",
      "/images/dave/_DSC6923.JPG.jpeg",
      "/images/dave/_DSC6924.JPG.jpeg",
      "/images/dave/_DSC6925.JPG.jpeg",
      "/images/dave/_DSC6926.JPG.jpeg",
      "/images/dave/_DSC6927.JPG.jpeg",
      "/images/dave/426dc132-789f-4d59-8444-4ff07f0f97d1.jpg",
    ],
    drawingImages: [
      { src: "/images/dave/drawings/final-floor-plan.jpg", label: "Floor Plan" },
      { src: "/images/dave/drawings/living-room.jpg", label: "Living Room" },
      { src: "/images/dave/drawings/master-bedroom.jpg", label: "Master Bedroom" },
      { src: "/images/dave/drawings/parents-bedroom.jpg", label: "Parents' Bedroom" },
      { src: "/images/dave/drawings/daughters-bedroom.jpg", label: "Daughter's Bedroom" },
      { src: "/images/dave/drawings/master-bathroom.jpg", label: "Master Bathroom" },
      { src: "/images/dave/drawings/mothers-bathroom.jpg", label: "Mother's Bathroom" },
      { src: "/images/dave/drawings/daughters-bathroom.jpg", label: "Daughter's Bathroom" },
      { src: "/images/dave/drawings/crockery-unit.jpg", label: "Crockery Unit" },
      { src: "/images/dave/drawings/fabric-selection.jpg", label: "Fabric Selection" },
    ],
    featured: true,
    order: 3,
  },
  {
    slug: "dalamal-office",
    name: "Dalamal Office",
    client: "Dalamal Office",
    category: "Commercial",
    type: "Commercial Office Interior",
    location: "Marine Lines",
    building: "Dalamal Tower",
    year: "Needs Clarification",
    status: "Completed",
    scope: [
      "Space Planning",
      "Reception Design",
      "Workstation Layout",
      "Cabin & Conference Design",
      "Ceiling & Lighting Design",
      "Material Selection",
    ],
    concept:
      "A professional workspace designed to feel open and contemporary despite its underground setting — strategic ceiling treatments, material choices, and lighting shift the perception from basement to modern office.",
    story:
      "The Dalamal Office at Marine Lines presented an inherent spatial challenge: creating an energising, professional work environment in a below-grade space with no access to natural daylight. The design response focused on perception rather than compensation. A skylight-inspired ceiling concept — using layered lighting and ceiling articulation — creates the illusion of height and openness. Black stone and brick cladding at the reception grounds the space with texture and materiality, while a carefully zoned plan separates the reception and waiting area from private cabins, conference room, and an open workstation grid serving over 30 desks.",
    heroImage: "/images/dalamal/drawings/reception-area.jpg",
    galleryImages: [],
    drawingImages: [
      { src: "/images/dalamal/drawings/master-plan.jpg", label: "Master Plan" },
      { src: "/images/dalamal/drawings/reception-area.jpg", label: "Reception Area" },
      { src: "/images/dalamal/drawings/conference-room.jpg", label: "Conference Room" },
      { src: "/images/dalamal/drawings/workstation.jpg", label: "Workstation" },
    ],
    featured: false,
    order: 4,
  },
  {
    slug: "thomas-residence",
    name: "Thomas Residence",
    client: "Thomas Residence",
    category: "Residential",
    type: "3BHK Residence",
    location: "Mahalakshmi",
    building: "Prestige Jasdan",
    year: "Needs Clarification",
    status: "In Progress",
    scope: [
      "Space Planning",
      "Master Bedroom Design",
      "His & Her Study Rooms",
      "Wardrobe Detailing",
      "Kitchen Planning",
      "Bar Unit Design",
      "Furniture Detailing",
    ],
    concept:
      "A semi-furnished residence designed for a couple — each space individually tailored to their lifestyles, with dedicated study rooms, a bespoke bar unit, and customised wardrobe solutions throughout.",
    story:
      "The Thomas Residence at Prestige Jasdan, Mahalakshmi is a considered home for two — where shared spaces open into deeply personal retreats. The design prioritised equal attention for both clients: her wardrobe and study were developed as a cohesive suite, while his library and wardrobe were designed with different character and detail. The master bedroom ties the two sensibilities together. A custom bar unit introduces warmth and social living into the home, while the kitchen planning maximises storage within the compact configuration. The project is currently in execution.",
    heroImage: "/images/thomas/2eb6699d-f4b9-4fea-a548-e23e46d4f13e.jpg",
    galleryImages: [
      "/images/thomas/2eb6699d-f4b9-4fea-a548-e23e46d4f13e.jpg",
      "/images/thomas/04bc5b37-fae0-438c-80c6-20b27daada1d.jpg",
      "/images/thomas/539e9617-0b43-4714-8528-82ccec10de6e.jpg",
      "/images/thomas/53a295d0-94db-4c72-958e-629d87e5a035.jpg",
      "/images/thomas/5c26ac08-605b-45fb-b2be-9574246aa236.jpg",
      "/images/thomas/738e070e-7b23-40c5-8a37-d3b496f82246.jpg",
      "/images/thomas/fbac55ba-635a-47e5-aa11-674fadbc3e45.jpg",
    ],
    drawingImages: [
      { src: "/images/thomas/drawings/master-bedroom-elevation.jpg", label: "Master Bedroom Elevation" },
      { src: "/images/thomas/drawings/master-wardrobe.jpg", label: "Master Wardrobe" },
      { src: "/images/thomas/drawings/master-bathroom.jpg", label: "Master Bathroom" },
      { src: "/images/thomas/drawings/bar-unit.jpg", label: "Bar Unit" },
      { src: "/images/thomas/drawings/his-wardrobe.jpg", label: "His Wardrobe" },
      { src: "/images/thomas/drawings/his-bathroom.jpg", label: "His Bathroom" },
      { src: "/images/thomas/drawings/his-library.jpg", label: "His Library" },
      { src: "/images/thomas/drawings/her-wardrobe-and-study.jpg", label: "Her Wardrobe & Study" },
      { src: "/images/thomas/drawings/her-bathroom.jpg", label: "Her Bathroom" },
    ],
    featured: false,
    order: 5,
  },
  {
    slug: "sonia-residence",
    name: "Sonia Agarwal Residence",
    client: "Sonia Agarwal Residence",
    category: "Renovation",
    type: "Residential Renovation",
    location: "Juhu",
    building: "",
    year: "Needs Clarification",
    status: "Completed",
    scope: [
      "Custom Furniture Design",
      "Wall Detailing",
      "Daughter's Bedroom Design",
      "Den Area Renovation",
    ],
    concept:
      "A renovation centred on custom craftsmanship — a richly panelled feature wall with hand-carved decorative appliqués transforms the den into a statement living space.",
    story:
      "The Sonia Agarwal Residence in Juhu was a targeted renovation focused on two spaces: the daughter's bedroom and the den area. The centrepiece of the project is a floor-to-ceiling wood-panelled feature wall in the living room — a classical composition of framed panels and hand-carved decorative mouldings in warm honey-toned wood, paired with a bespoke grey sectional sofa. The result is a room that reads as both grand and intimately personal.",
    heroImage: "/images/sonia/25d126ff-b219-4e30-892d-4d4e5f163772.jpg",
    galleryImages: [
      "/images/sonia/25d126ff-b219-4e30-892d-4d4e5f163772.jpg",
      "/images/sonia/7d8a1b8b-ee10-4f21-ab4c-d40fef1d1dce.jpg",
    ],
    drawingImages: [],
    featured: false,
    order: 6,
  },
  {
    slug: "burzin-duplex",
    name: "Burzin Duplex",
    client: "Burzin Duplex",
    category: "Residential",
    type: "Duplex Residence",
    location: "Colaba",
    building: "Cusrow Baug",
    year: "Needs Clarification",
    status: "Design Phase",
    scope: [
      "Space Planning",
      "Mezzanine Floor Design",
      "Elevation Design",
      "Material & Wallpaper Selection",
      "Furniture Layout Planning",
      "Bar Counter Design",
    ],
    concept:
      "A vintage-inspired duplex that embraces texture and character — 'Faux Caning' wallpaper, mezzanine living, and curated furnishings create a home with the warmth of a collector's residence.",
    story:
      "The Burzin Duplex at Cusrow Baug, Colaba — one of Mumbai's most storied heritage enclaves — inspired a design approach rooted in vintage character and crafted detail. The mezzanine floor configuration was embraced as a design asset, creating distinct spatial zones across levels while maintaining visual connectivity. 'Faux Caning' wallpaper in Umber tones establishes the material language, complemented by a carefully planned bar counter and furnishings that reference mid-century and artisanal aesthetics. The project is currently in design development.",
    heroImage: "/images/burzin/drawings/floor-plan.jpg",
    galleryImages: [],
    drawingImages: [
      { src: "/images/burzin/drawings/floor-plan.jpg", label: "Floor Plan" },
      { src: "/images/burzin/drawings/elevations.jpg", label: "Elevations" },
    ],
    featured: false,
    order: 7,
  },
  {
    slug: "alyza-residence",
    name: "Alyza Residence",
    client: "Alyza Residence",
    category: "Furniture Design",
    type: "Custom Furniture Design",
    location: "Lower Parel",
    building: "Raheja Towers",
    year: "Needs Clarification",
    status: "Completed",
    scope: [
      "Custom Furniture Design",
      "Production Drawing",
      "Living Room Furniture Layout",
    ],
    concept:
      "A Pinterest-inspired custom furniture brief translated into precise production drawings — demonstrating the full journey from client vision to manufacturable design.",
    story:
      "The Alyza Residence project at Raheja Towers, Lower Parel was a focused furniture design commission: take the client's curated visual references and translate them into a buildable, dimensioned set of custom living room furniture. The process involved detailed measurement, layout planning within the space, and the production of precise working drawings ready for fabrication.",
    heroImage: "/images/alyza/drawings/furniture-layout.jpg",
    galleryImages: [],
    drawingImages: [
      { src: "/images/alyza/drawings/furniture-layout.jpg", label: "Furniture Layout" },
    ],
    featured: false,
    order: 8,
  },
];

export default projects;

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getFeaturedProjects(): Project[] {
  return projects.filter((p) => p.featured).sort((a, b) => a.order - b.order);
}

export function getAllProjects(): Project[] {
  return projects.sort((a, b) => a.order - b.order);
}
